package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   购物车
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_CART
 */
public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   是否选择,1=已勾选,0=未勾选
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.CHECKED
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer checked;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CART.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Cart(Integer id, Integer userId, Integer productId, Integer quantity, Integer checked, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.productId = productId;
        this.quantity = quantity;
        this.checked = checked;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Cart() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.ID
     *
     * @return the value of MARKET_CART.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.ID
     *
     * @param id the value for MARKET_CART.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.USER_ID
     *
     * @return the value of MARKET_CART.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.USER_ID
     *
     * @param userId the value for MARKET_CART.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.PRODUCT_ID
     *
     * @return the value of MARKET_CART.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.PRODUCT_ID
     *
     * @param productId the value for MARKET_CART.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.QUANTITY
     *
     * @return the value of MARKET_CART.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.QUANTITY
     *
     * @param quantity the value for MARKET_CART.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.CHECKED
     *
     * @return the value of MARKET_CART.CHECKED
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.CHECKED
     *
     * @param checked the value for MARKET_CART.CHECKED
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.CREATE_TIME
     *
     * @return the value of MARKET_CART.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.CREATE_TIME
     *
     * @param createTime the value for MARKET_CART.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CART.UPDATE_TIME
     *
     * @return the value of MARKET_CART.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CART.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_CART.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}