package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   目录
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_CATEGORY
 */
public class Category {
    /**
     * Database Column Remarks:
     *   类别Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父类别id当id=0时说明是根节点,一级类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.PARENT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String name;

    /**
     * Database Column Remarks:
     *   类别状态1-正常,2-已废弃
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private byte[] status;

    /**
     * Database Column Remarks:
     *   排序编号,同类展示顺序,数值相等则自然排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.SORT_ORDER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer sortOrder;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_CATEGORY.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CATEGORY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Category(Integer id, Integer parentId, String name, byte[] status, Integer sortOrder, Date createTime, Date updateTime) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.status = status;
        this.sortOrder = sortOrder;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CATEGORY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.ID
     *
     * @return the value of MARKET_CATEGORY.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.ID
     *
     * @param id the value for MARKET_CATEGORY.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.PARENT_ID
     *
     * @return the value of MARKET_CATEGORY.PARENT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.PARENT_ID
     *
     * @param parentId the value for MARKET_CATEGORY.PARENT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.NAME
     *
     * @return the value of MARKET_CATEGORY.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.NAME
     *
     * @param name the value for MARKET_CATEGORY.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.STATUS
     *
     * @return the value of MARKET_CATEGORY.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public byte[] getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.STATUS
     *
     * @param status the value for MARKET_CATEGORY.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setStatus(byte[] status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.SORT_ORDER
     *
     * @return the value of MARKET_CATEGORY.SORT_ORDER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.SORT_ORDER
     *
     * @param sortOrder the value for MARKET_CATEGORY.SORT_ORDER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.CREATE_TIME
     *
     * @return the value of MARKET_CATEGORY.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.CREATE_TIME
     *
     * @param createTime the value for MARKET_CATEGORY.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_CATEGORY.UPDATE_TIME
     *
     * @return the value of MARKET_CATEGORY.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_CATEGORY.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_CATEGORY.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}