package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_USER
 */
public class MarketUser {
    /**
     * Database Column Remarks:
     *   用户表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.USERNAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String username;

    /**
     * Database Column Remarks:
     *   用户密码，MD5加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.PASSWORD
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.EMAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   找回密码问题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.QUESTION
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String question;

    /**
     * Database Column Remarks:
     *   找回密码答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.ANSWER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String answer;

    /**
     * Database Column Remarks:
     *   角色0-管理员,1-普通用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.ROLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer role;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   最后一次更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_USER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_USER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public MarketUser(Integer id, String username, String password, String email, String phone, String question, String answer, Integer role, Date createTime, Date updateTime) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.phone = phone;
        this.question = question;
        this.answer = answer;
        this.role = role;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_USER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public MarketUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.ID
     *
     * @return the value of MARKET_USER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.ID
     *
     * @param id the value for MARKET_USER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.USERNAME
     *
     * @return the value of MARKET_USER.USERNAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.USERNAME
     *
     * @param username the value for MARKET_USER.USERNAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.PASSWORD
     *
     * @return the value of MARKET_USER.PASSWORD
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.PASSWORD
     *
     * @param password the value for MARKET_USER.PASSWORD
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.EMAIL
     *
     * @return the value of MARKET_USER.EMAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.EMAIL
     *
     * @param email the value for MARKET_USER.EMAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.PHONE
     *
     * @return the value of MARKET_USER.PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.PHONE
     *
     * @param phone the value for MARKET_USER.PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.QUESTION
     *
     * @return the value of MARKET_USER.QUESTION
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.QUESTION
     *
     * @param question the value for MARKET_USER.QUESTION
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.ANSWER
     *
     * @return the value of MARKET_USER.ANSWER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.ANSWER
     *
     * @param answer the value for MARKET_USER.ANSWER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.ROLE
     *
     * @return the value of MARKET_USER.ROLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.ROLE
     *
     * @param role the value for MARKET_USER.ROLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.CREATE_TIME
     *
     * @return the value of MARKET_USER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.CREATE_TIME
     *
     * @param createTime the value for MARKET_USER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_USER.UPDATE_TIME
     *
     * @return the value of MARKET_USER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_USER.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_USER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}