package com.raysaber.market.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   订单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_ORDER
 */
public class Order {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Long orderNo;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.SHIPPING_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer shippingId;

    /**
     * Database Column Remarks:
     *   实际付款金额,单位是元,保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.PAYMENT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private BigDecimal payment;

    /**
     * Database Column Remarks:
     *   支付类型,1-在线支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.PAYMENT_TYPE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer paymentType;

    /**
     * Database Column Remarks:
     *   运费,单位是元
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.POSTAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer postage;

    /**
     * Database Column Remarks:
     *   订单状态:0-已取消-10-未付款，20-已付款，40-已发货，50-交易成功，60-交易关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.PAYMENT_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date paymentTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.SEND_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date sendTime;

    /**
     * Database Column Remarks:
     *   交易完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.END_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   交易关闭时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.CLOSE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date closeTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Order(Integer id, Long orderNo, Integer userId, Integer shippingId, BigDecimal payment, Integer paymentType, Integer postage, Integer status, Date paymentTime, Date sendTime, Date endTime, Date closeTime, Date createTime, Date updateTime) {
        this.id = id;
        this.orderNo = orderNo;
        this.userId = userId;
        this.shippingId = shippingId;
        this.payment = payment;
        this.paymentType = paymentType;
        this.postage = postage;
        this.status = status;
        this.paymentTime = paymentTime;
        this.sendTime = sendTime;
        this.endTime = endTime;
        this.closeTime = closeTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Order() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.ID
     *
     * @return the value of MARKET_ORDER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.ID
     *
     * @param id the value for MARKET_ORDER.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.ORDER_NO
     *
     * @return the value of MARKET_ORDER.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.ORDER_NO
     *
     * @param orderNo the value for MARKET_ORDER.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.USER_ID
     *
     * @return the value of MARKET_ORDER.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.USER_ID
     *
     * @param userId the value for MARKET_ORDER.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.SHIPPING_ID
     *
     * @return the value of MARKET_ORDER.SHIPPING_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.SHIPPING_ID
     *
     * @param shippingId the value for MARKET_ORDER.SHIPPING_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.PAYMENT
     *
     * @return the value of MARKET_ORDER.PAYMENT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.PAYMENT
     *
     * @param payment the value for MARKET_ORDER.PAYMENT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.PAYMENT_TYPE
     *
     * @return the value of MARKET_ORDER.PAYMENT_TYPE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.PAYMENT_TYPE
     *
     * @param paymentType the value for MARKET_ORDER.PAYMENT_TYPE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.POSTAGE
     *
     * @return the value of MARKET_ORDER.POSTAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.POSTAGE
     *
     * @param postage the value for MARKET_ORDER.POSTAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.STATUS
     *
     * @return the value of MARKET_ORDER.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.STATUS
     *
     * @param status the value for MARKET_ORDER.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.PAYMENT_TIME
     *
     * @return the value of MARKET_ORDER.PAYMENT_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.PAYMENT_TIME
     *
     * @param paymentTime the value for MARKET_ORDER.PAYMENT_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.SEND_TIME
     *
     * @return the value of MARKET_ORDER.SEND_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.SEND_TIME
     *
     * @param sendTime the value for MARKET_ORDER.SEND_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.END_TIME
     *
     * @return the value of MARKET_ORDER.END_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.END_TIME
     *
     * @param endTime the value for MARKET_ORDER.END_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.CLOSE_TIME
     *
     * @return the value of MARKET_ORDER.CLOSE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.CLOSE_TIME
     *
     * @param closeTime the value for MARKET_ORDER.CLOSE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.CREATE_TIME
     *
     * @return the value of MARKET_ORDER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.CREATE_TIME
     *
     * @param createTime the value for MARKET_ORDER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER.UPDATE_TIME
     *
     * @return the value of MARKET_ORDER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_ORDER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}