package com.raysaber.market.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   订单子表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_ORDER_ITEM
 */
public class OrderItem {
    /**
     * Database Column Remarks:
     *   订单子表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Long orderNo;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   商品图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.PRODUCT_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String productImage;

    /**
     * Database Column Remarks:
     *   生成订单时的商品单价，单位是元,保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.CURRENT_UNIT_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private BigDecimal currentUnitPrice;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   商品总价,单位是元,保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.TOTAL_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_ORDER_ITEM.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public OrderItem(Integer id, Integer userId, Long orderNo, Integer productId, String productName, String productImage, BigDecimal currentUnitPrice, Integer quantity, BigDecimal totalPrice, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.orderNo = orderNo;
        this.productId = productId;
        this.productName = productName;
        this.productImage = productImage;
        this.currentUnitPrice = currentUnitPrice;
        this.quantity = quantity;
        this.totalPrice = totalPrice;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public OrderItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.ID
     *
     * @return the value of MARKET_ORDER_ITEM.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.ID
     *
     * @param id the value for MARKET_ORDER_ITEM.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.USER_ID
     *
     * @return the value of MARKET_ORDER_ITEM.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.USER_ID
     *
     * @param userId the value for MARKET_ORDER_ITEM.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.ORDER_NO
     *
     * @return the value of MARKET_ORDER_ITEM.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.ORDER_NO
     *
     * @param orderNo the value for MARKET_ORDER_ITEM.ORDER_NO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.PRODUCT_ID
     *
     * @return the value of MARKET_ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.PRODUCT_ID
     *
     * @param productId the value for MARKET_ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.PRODUCT_NAME
     *
     * @return the value of MARKET_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.PRODUCT_NAME
     *
     * @param productName the value for MARKET_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.PRODUCT_IMAGE
     *
     * @return the value of MARKET_ORDER_ITEM.PRODUCT_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.PRODUCT_IMAGE
     *
     * @param productImage the value for MARKET_ORDER_ITEM.PRODUCT_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.CURRENT_UNIT_PRICE
     *
     * @return the value of MARKET_ORDER_ITEM.CURRENT_UNIT_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.CURRENT_UNIT_PRICE
     *
     * @param currentUnitPrice the value for MARKET_ORDER_ITEM.CURRENT_UNIT_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.QUANTITY
     *
     * @return the value of MARKET_ORDER_ITEM.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.QUANTITY
     *
     * @param quantity the value for MARKET_ORDER_ITEM.QUANTITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.TOTAL_PRICE
     *
     * @return the value of MARKET_ORDER_ITEM.TOTAL_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.TOTAL_PRICE
     *
     * @param totalPrice the value for MARKET_ORDER_ITEM.TOTAL_PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.CREATE_TIME
     *
     * @return the value of MARKET_ORDER_ITEM.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.CREATE_TIME
     *
     * @param createTime the value for MARKET_ORDER_ITEM.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_ORDER_ITEM.UPDATE_TIME
     *
     * @return the value of MARKET_ORDER_ITEM.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_ORDER_ITEM.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_ORDER_ITEM.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}