package com.raysaber.market.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   产品信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_PRODUCT
 */
public class Product {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   分类id,对应mmall_category表的主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品副标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.SUBTITLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String subtitle;

    /**
     * Database Column Remarks:
     *   产品主图,url相对地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.MAIN_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String mainImage;

    /**
     * Database Column Remarks:
     *   价格,单位-元保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.STOCK
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   商品状态.1-在售 2-下架 3-删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Product(Integer id, Integer categoryId, String name, String subtitle, String mainImage, BigDecimal price, Integer stock, Integer status, Date createTime, Date updateTime) {
        this.id = id;
        this.categoryId = categoryId;
        this.name = name;
        this.subtitle = subtitle;
        this.mainImage = mainImage;
        this.price = price;
        this.stock = stock;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.ID
     *
     * @return the value of MARKET_PRODUCT.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.ID
     *
     * @param id the value for MARKET_PRODUCT.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.CATEGORY_ID
     *
     * @return the value of MARKET_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.CATEGORY_ID
     *
     * @param categoryId the value for MARKET_PRODUCT.CATEGORY_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.NAME
     *
     * @return the value of MARKET_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.NAME
     *
     * @param name the value for MARKET_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.SUBTITLE
     *
     * @return the value of MARKET_PRODUCT.SUBTITLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.SUBTITLE
     *
     * @param subtitle the value for MARKET_PRODUCT.SUBTITLE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.MAIN_IMAGE
     *
     * @return the value of MARKET_PRODUCT.MAIN_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.MAIN_IMAGE
     *
     * @param mainImage the value for MARKET_PRODUCT.MAIN_IMAGE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.PRICE
     *
     * @return the value of MARKET_PRODUCT.PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.PRICE
     *
     * @param price the value for MARKET_PRODUCT.PRICE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.STOCK
     *
     * @return the value of MARKET_PRODUCT.STOCK
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.STOCK
     *
     * @param stock the value for MARKET_PRODUCT.STOCK
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.STATUS
     *
     * @return the value of MARKET_PRODUCT.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.STATUS
     *
     * @param status the value for MARKET_PRODUCT.STATUS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.CREATE_TIME
     *
     * @return the value of MARKET_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.CREATE_TIME
     *
     * @param createTime the value for MARKET_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.UPDATE_TIME
     *
     * @return the value of MARKET_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}