package com.raysaber.market.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   产品信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_PRODUCT
 */
public class ProductWithBLOBs extends Product {
    /**
     * Database Column Remarks:
     *   图片地址,json格式,扩展用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.SUB_IMAGES
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String subImages;

    /**
     * Database Column Remarks:
     *   商品详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_PRODUCT.DETAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public ProductWithBLOBs(Integer id, Integer categoryId, String name, String subtitle, String mainImage, BigDecimal price, Integer stock, Integer status, Date createTime, Date updateTime, String subImages, String detail) {
        super(id, categoryId, name, subtitle, mainImage, price, stock, status, createTime, updateTime);
        this.subImages = subImages;
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public ProductWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.SUB_IMAGES
     *
     * @return the value of MARKET_PRODUCT.SUB_IMAGES
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.SUB_IMAGES
     *
     * @param subImages the value for MARKET_PRODUCT.SUB_IMAGES
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_PRODUCT.DETAIL
     *
     * @return the value of MARKET_PRODUCT.DETAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_PRODUCT.DETAIL
     *
     * @param detail the value for MARKET_PRODUCT.DETAIL
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}