package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   角色表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ROLE_TABLE
 */
public class Role {
    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Long sid;

    /**
     * Database Column Remarks:
     *   角色名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.ROLE_NAME
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   创建者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.CREATE_MAN_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String createManUuid;

    /**
     * Database Column Remarks:
     *   角色唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String roleUuid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Role(Long sid, String roleName, String createManUuid, String roleUuid, Date createDate, Date updateDate) {
        this.sid = sid;
        this.roleName = roleName;
        this.createManUuid = createManUuid;
        this.roleUuid = roleUuid;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.SID
     *
     * @return the value of ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.SID
     *
     * @param sid the value for ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.ROLE_NAME
     *
     * @return the value of ROLE_TABLE.ROLE_NAME
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.ROLE_NAME
     *
     * @param roleName the value for ROLE_TABLE.ROLE_NAME
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.CREATE_MAN_UUID
     *
     * @return the value of ROLE_TABLE.CREATE_MAN_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getCreateManUuid() {
        return createManUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.CREATE_MAN_UUID
     *
     * @param createManUuid the value for ROLE_TABLE.CREATE_MAN_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setCreateManUuid(String createManUuid) {
        this.createManUuid = createManUuid == null ? null : createManUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.ROLE_UUID
     *
     * @return the value of ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.ROLE_UUID
     *
     * @param roleUuid the value for ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.CREATE_DATE
     *
     * @return the value of ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.CREATE_DATE
     *
     * @param createDate the value for ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_TABLE.UPDATE_DATE
     *
     * @return the value of ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_TABLE.UPDATE_DATE
     *
     * @param updateDate the value for ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}