package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   角色权限关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ROLE_PERMISSION_TABLE
 */
public class RolePermission {
    /**
     * Database Column Remarks:
     *   关联表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Long sid;

    /**
     * Database Column Remarks:
     *   角色唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String roleUuid;

    /**
     * Database Column Remarks:
     *   权限唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION_TABLE.PERMISSION_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String permissionUuid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public RolePermission(Long sid, String roleUuid, String permissionUuid, Date createDate, Date updateDate) {
        this.sid = sid;
        this.roleUuid = roleUuid;
        this.permissionUuid = permissionUuid;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public RolePermission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION_TABLE.SID
     *
     * @return the value of ROLE_PERMISSION_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION_TABLE.SID
     *
     * @param sid the value for ROLE_PERMISSION_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION_TABLE.ROLE_UUID
     *
     * @return the value of ROLE_PERMISSION_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION_TABLE.ROLE_UUID
     *
     * @param roleUuid the value for ROLE_PERMISSION_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION_TABLE.PERMISSION_UUID
     *
     * @return the value of ROLE_PERMISSION_TABLE.PERMISSION_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getPermissionUuid() {
        return permissionUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION_TABLE.PERMISSION_UUID
     *
     * @param permissionUuid the value for ROLE_PERMISSION_TABLE.PERMISSION_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setPermissionUuid(String permissionUuid) {
        this.permissionUuid = permissionUuid == null ? null : permissionUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION_TABLE.CREATE_DATE
     *
     * @return the value of ROLE_PERMISSION_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION_TABLE.CREATE_DATE
     *
     * @param createDate the value for ROLE_PERMISSION_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION_TABLE.UPDATE_DATE
     *
     * @return the value of ROLE_PERMISSION_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION_TABLE.UPDATE_DATE
     *
     * @param updateDate the value for ROLE_PERMISSION_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}