package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   邮寄信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table MARKET_SHIPPING
 */
public class Shipping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   收货姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverName;

    /**
     * Database Column Remarks:
     *   收货固定电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverPhone;

    /**
     * Database Column Remarks:
     *   收货移动电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverMobile;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_PROVINCE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverProvince;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_CITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverCity;

    /**
     * Database Column Remarks:
     *   区/县
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverDistrict;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverAddress;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.RECEIVER_ZIP
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private String receiverZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MARKET_SHIPPING.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_SHIPPING
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Shipping(Integer id, Integer userId, String receiverName, String receiverPhone, String receiverMobile, String receiverProvince, String receiverCity, String receiverDistrict, String receiverAddress, String receiverZip, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.receiverName = receiverName;
        this.receiverPhone = receiverPhone;
        this.receiverMobile = receiverMobile;
        this.receiverProvince = receiverProvince;
        this.receiverCity = receiverCity;
        this.receiverDistrict = receiverDistrict;
        this.receiverAddress = receiverAddress;
        this.receiverZip = receiverZip;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_SHIPPING
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Shipping() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.ID
     *
     * @return the value of MARKET_SHIPPING.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.ID
     *
     * @param id the value for MARKET_SHIPPING.ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.USER_ID
     *
     * @return the value of MARKET_SHIPPING.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.USER_ID
     *
     * @param userId the value for MARKET_SHIPPING.USER_ID
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_NAME
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_NAME
     *
     * @param receiverName the value for MARKET_SHIPPING.RECEIVER_NAME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_PHONE
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_PHONE
     *
     * @param receiverPhone the value for MARKET_SHIPPING.RECEIVER_PHONE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_MOBILE
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_MOBILE
     *
     * @param receiverMobile the value for MARKET_SHIPPING.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_PROVINCE
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_PROVINCE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_PROVINCE
     *
     * @param receiverProvince the value for MARKET_SHIPPING.RECEIVER_PROVINCE
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince == null ? null : receiverProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_CITY
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_CITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_CITY
     *
     * @param receiverCity the value for MARKET_SHIPPING.RECEIVER_CITY
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_DISTRICT
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_DISTRICT
     *
     * @param receiverDistrict the value for MARKET_SHIPPING.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_ADDRESS
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_ADDRESS
     *
     * @param receiverAddress the value for MARKET_SHIPPING.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.RECEIVER_ZIP
     *
     * @return the value of MARKET_SHIPPING.RECEIVER_ZIP
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.RECEIVER_ZIP
     *
     * @param receiverZip the value for MARKET_SHIPPING.RECEIVER_ZIP
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.CREATE_TIME
     *
     * @return the value of MARKET_SHIPPING.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.CREATE_TIME
     *
     * @param createTime the value for MARKET_SHIPPING.CREATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MARKET_SHIPPING.UPDATE_TIME
     *
     * @return the value of MARKET_SHIPPING.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MARKET_SHIPPING.UPDATE_TIME
     *
     * @param updateTime the value for MARKET_SHIPPING.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}