package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table USER_TABLE
 */
public class User {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Long sid;

    /**
     * Database Column Remarks:
     *   用户账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_ACCOUNT
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String userAccount;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_PWD
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String userPwd;

    /**
     * Database Column Remarks:
     *   用户唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String userUuid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public User(Long sid, String userAccount, String userPwd, String userUuid, Date createDate, Date updateDate) {
        this.sid = sid;
        this.userAccount = userAccount;
        this.userPwd = userPwd;
        this.userUuid = userUuid;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.SID
     *
     * @return the value of USER_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.SID
     *
     * @param sid the value for USER_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_ACCOUNT
     *
     * @return the value of USER_TABLE.USER_ACCOUNT
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_ACCOUNT
     *
     * @param userAccount the value for USER_TABLE.USER_ACCOUNT
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_PWD
     *
     * @return the value of USER_TABLE.USER_PWD
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_PWD
     *
     * @param userPwd the value for USER_TABLE.USER_PWD
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_UUID
     *
     * @return the value of USER_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_UUID
     *
     * @param userUuid the value for USER_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.CREATE_DATE
     *
     * @return the value of USER_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.CREATE_DATE
     *
     * @param createDate the value for USER_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.UPDATE_DATE
     *
     * @return the value of USER_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.UPDATE_DATE
     *
     * @param updateDate the value for USER_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}