package com.raysaber.market.bean;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户角色关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table USER_ROLE_TABLE
 */
public class UserRole {
    /**
     * Database Column Remarks:
     *   关联表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Long sid;

    /**
     * Database Column Remarks:
     *   用户唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String userUuid;

    /**
     * Database Column Remarks:
     *   角色唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private String roleUuid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public UserRole(Long sid, String userUuid, String roleUuid, Date createDate, Date updateDate) {
        this.sid = sid;
        this.userUuid = userUuid;
        this.roleUuid = roleUuid;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public UserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE_TABLE.SID
     *
     * @return the value of USER_ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE_TABLE.SID
     *
     * @param sid the value for USER_ROLE_TABLE.SID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE_TABLE.USER_UUID
     *
     * @return the value of USER_ROLE_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE_TABLE.USER_UUID
     *
     * @param userUuid the value for USER_ROLE_TABLE.USER_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE_TABLE.ROLE_UUID
     *
     * @return the value of USER_ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE_TABLE.ROLE_UUID
     *
     * @param roleUuid the value for USER_ROLE_TABLE.ROLE_UUID
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE_TABLE.CREATE_DATE
     *
     * @return the value of USER_ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE_TABLE.CREATE_DATE
     *
     * @param createDate the value for USER_ROLE_TABLE.CREATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE_TABLE.UPDATE_DATE
     *
     * @return the value of USER_ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE_TABLE.UPDATE_DATE
     *
     * @param updateDate the value for USER_ROLE_TABLE.UPDATE_DATE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}