package com.raysaber.market.dao;

import com.raysaber.market.bean.Cart;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_CART
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKey(Cart record);
}