package com.raysaber.market.dao;

import com.raysaber.market.bean.OrderItem;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_ORDER_ITEM
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKey(OrderItem record);
}