package com.raysaber.market.dao;

import com.raysaber.market.bean.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PAY_INFO
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKey(PayInfo record);
}