package com.raysaber.market.dao;

import com.raysaber.market.bean.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    Permission selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKey(Permission record);
}