package com.raysaber.market.dao;

import com.raysaber.market.bean.Product;
import com.raysaber.market.bean.ProductWithBLOBs;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int insertSelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    ProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKeySelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MARKET_PRODUCT
     *
     * @mbg.generated Tue Apr 20 04:08:53 CST 2021
     */
    int updateByPrimaryKey(Product record);
}