package com.raysaber.market.dao;

import com.raysaber.market.bean.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    RolePermission selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKey(RolePermission record);
}