package com.raysaber.market.dao;

import com.raysaber.market.bean.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    Role selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKey(Role record);
}