package com.raysaber.market.dao;

import com.raysaber.market.bean.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    UserRole selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKey(UserRole record);
}