package com.raysaber.market.dao;

import com.raysaber.market.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    User selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbg.generated Tue Apr 20 04:22:09 CST 2021
     */
    int updateByPrimaryKey(User record);
}